name = "bahamut-daily-bonus"
main = "src/index.ts"
compatibility_date = "2024-12-01"
node_compat = true

[vars]
# 環境變數配置

# 定時任務設定 - 每天早上 8:00 執行 (UTC+8)
[triggers]
crons = ["0 0 * * *"]

# 機密資料使用 wrangler secret 設定
# wrangler secret put BAHAMUT_UID
# wrangler secret put BAHAMUT_PWD
# wrangler secret put BAHAMUT_TOTP (選填)
# wrangler secret put TELEGRAM_BOT_TOKEN (選填，Telegram Bot Token)
# wrangler secret put TELEGRAM_CHAT_ID (選填，Telegram Chat ID)